# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "service".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  nginx:
      image: nginx:latest
      hostname: nginx
      container_name: nginx
      platform: linux/amd64
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - service
      networks:
        - application
  service:
    hostname: service
    container_name: service
    build:
      context: .
    volumes:
      - ./.cache/logs:/app/logs/
    networks:
        - application
networks:
  application: